// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-9zq2CZUygF2_RCOGacJHoQtYBWrRF-8',
    appId: '1:953336535531:web:35bdd5bf322f6f91b561ae',
    messagingSenderId: '953336535531',
    projectId: 'stock-market-9083f',
    authDomain: 'stock-market-9083f.firebaseapp.com',
    storageBucket: 'stock-market-9083f.appspot.com',
    measurementId: 'G-XDS47JXVEX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcTIorauwFii5jjK_ers3KW8HTXlBmnu4',
    appId: '1:953336535531:android:3161791bcb2e6663b561ae',
    messagingSenderId: '953336535531',
    projectId: 'stock-market-9083f',
    storageBucket: 'stock-market-9083f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDXcK12YwGQ4NY_SJoLgEmM5lSiIjNxMPw',
    appId: '1:953336535531:ios:0fcfe0e9c66e2c15b561ae',
    messagingSenderId: '953336535531',
    projectId: 'stock-market-9083f',
    storageBucket: 'stock-market-9083f.appspot.com',
    iosBundleId: 'com.example.stockMarket',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDXcK12YwGQ4NY_SJoLgEmM5lSiIjNxMPw',
    appId: '1:953336535531:ios:4f33e673d9d0d8dfb561ae',
    messagingSenderId: '953336535531',
    projectId: 'stock-market-9083f',
    storageBucket: 'stock-market-9083f.appspot.com',
    iosBundleId: 'com.example.stockMarket.RunnerTests',
  );
}
